import {escapeHtml,nativeBody} from './format.mjs';

export function preview({title,html},profile='x-native-underline-v2'){
  const initial=profile==='design-full-v1'?'design':'native';
  const nativeProfile=profile==='x-native-bold-v1'?profile:'x-native-underline-v2';
  const native=nativeBody(html,nativeProfile,{imageMarkers:false});
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>${escapeHtml(title)}</title><style>
*{box-sizing:border-box}body{--bg:#fff;--ink:#181b1e;--line:#dedfe2;--accent:#b42d24;--soft:#111;--onsoft:#f8f6f0;margin:0;background:var(--bg);color:var(--ink);font-family:-apple-system,BlinkMacSystemFont,'PingFang SC','Microsoft YaHei',sans-serif;letter-spacing:0}body.dark{--bg:#111416;--ink:#e8e9e7;--line:#42474b;--accent:#ff9d92;--soft:#e8e9e7;--onsoft:#151719;color-scheme:dark}nav{display:flex;flex-wrap:wrap;gap:8px;border-bottom:1px solid var(--line);padding:14px 20px}button,select{font:inherit;font-size:13px;background:var(--bg);color:var(--ink);border:1px solid var(--line);padding:8px 12px;border-radius:4px;cursor:pointer}button[aria-pressed=true]{background:var(--ink);color:var(--bg)}header,article{max-width:768px;margin:40px auto;padding:0 24px}h1{font-size:34px;line-height:1.5;overflow-wrap:anywhere}article{font-size:18px;line-height:1.95}p{margin:0 0 24px}h2{border-top:1px solid var(--line);padding-top:24px;margin:48px 0 24px;font-size:25px;line-height:1.55}h3{font-size:21px;line-height:1.6;margin:36px 0 20px}li{margin:10px 0}ul,ol{padding-left:1.5em}u{text-decoration-thickness:1px;text-underline-offset:4px}blockquote{margin:26px 0;padding:0 0 0 20px;border-left:3px solid var(--line)}blockquote p{margin:0}a{color:#286a9f;overflow-wrap:anywhere}.dark a{color:#9ac9e9}img{display:block;max-width:100%;height:auto;margin:30px auto}pre{overflow:auto;border:1px solid var(--line);padding:16px}code{font-family:ui-monospace,monospace;font-size:.9em}table{display:block;overflow:auto;border-collapse:collapse}td,th{padding:8px;border:1px solid var(--line)}.design .keyword{font-weight:800;text-decoration:none;border-bottom:3px solid var(--accent)}.design .anchor{color:var(--accent);font-weight:800}.design .highlight{background:var(--soft);color:var(--onsoft);padding:2px 6px;font-weight:800;box-decoration-break:clone;-webkit-box-decoration-break:clone}.design blockquote{background:#111;color:#f8f6f0;border-color:#b42d24;padding:22px;font-weight:700}.missing{text-align:center;padding:24px;border:1px solid var(--line)}[hidden]{display:none!important}#status{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);background:#242729;color:#fff;padding:10px 16px;max-width:90%;font-size:13px}#status:empty{display:none}@media(max-width:600px){h1{font-size:27px}article{font-size:17px}h2{font-size:23px}header,article{padding:0 22px}}
</style></head><body class="${initial}"><nav><button data-mode="native" aria-pressed="${initial==='native'}">X 原生版</button><button data-mode="design" aria-pressed="${initial==='design'}">完整设计版</button><button id="copy-title">复制标题</button><button id="copy-native">复制 X 正文</button><button id="copy-design">复制设计富文本</button><button id="theme" aria-pressed="false">深色预览</button></nav><header><h1>${escapeHtml(title)}</h1></header><article id="native" ${initial==='native'?'':'hidden'}>${native}</article><article id="design" ${initial==='design'?'':'hidden'}>${html}</article><div id="status" role="status"></div><script>
function mode(value){document.body.classList.toggle('design',value==='design');document.body.classList.toggle('native',value==='native');document.querySelectorAll('article').forEach(el=>el.hidden=el.id!==value);document.querySelectorAll('[data-mode]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.mode===value)))}
document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>mode(button.dataset.mode));
document.querySelector('#theme').onclick=e=>{const dark=document.body.classList.toggle('dark');e.currentTarget.textContent=dark?'浅色预览':'深色预览';e.currentTarget.setAttribute('aria-pressed',String(dark))};
function notice(message){document.querySelector('#status').textContent=message;setTimeout(()=>document.querySelector('#status').textContent='',6000)}
function prepare(kind){const previous=document.body.classList.contains('design')?'design':'native';mode(kind);const source=document.querySelector('#'+kind),clone=source.cloneNode(true);if(kind==='design'){const originals=[source,...source.querySelectorAll('*')];[clone,...clone.querySelectorAll('*')].forEach((node,i)=>{const computed=getComputedStyle(originals[i]);for(const key of ['color','background-color','font-size','font-weight','font-family','line-height','text-decoration','border-bottom','border-left','padding','margin','box-decoration-break'])node.style.setProperty(key,computed.getPropertyValue(key))})}clone.querySelectorAll('img').forEach((img,i)=>{const p=document.createElement('p');p.textContent='〖插入图 '+(img.getAttribute('data-media-index')||i+1)+'〗';img.replaceWith(p)});[clone,...clone.querySelectorAll('*')].forEach(node=>{node.removeAttribute('id');node.removeAttribute('class');node.removeAttribute('hidden');node.removeAttribute('data-media-index')});const plain=clone.cloneNode(true);plain.querySelectorAll('p,h2,h3,h4,li,blockquote,pre').forEach(el=>el.append(document.createTextNode('\\n\\n')));mode(previous);return{html:kind==='design'?clone.outerHTML:clone.innerHTML,text:plain.textContent.trim()}}
async function copy(html,text){try{if(html&&window.ClipboardItem)await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([text],{type:'text/plain'})})]);else await navigator.clipboard.writeText(text)}catch(error){const el=document.createElement('div');el.contentEditable=true;el.style.cssText='position:fixed;left:-9999px';if(html)el.innerHTML=html;else el.textContent=text;document.body.append(el);const range=document.createRange();range.selectNodeContents(el);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);const ok=document.execCommand('copy');selection.removeAllRanges();el.remove();if(!ok)throw error}}
document.querySelector('#copy-title').onclick=async()=>{try{await copy(null,document.querySelector('h1').textContent);notice('标题已复制')}catch{notice('复制失败，请手动选择标题')}};
for(const kind of ['native','design'])document.querySelector('#copy-'+kind).onclick=async()=>{try{const value=prepare(kind);await copy(value.html,value.text);notice(kind==='native'?'X 正文已复制；图片请按编号上传':'设计富文本已复制；目标编辑器可能过滤样式')}catch{notice('复制失败，请手动选择正文')}};
</script></body></html>`;
}
